# version: '3.8'
services:
  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    environment:
      # Override endpoints to point to local containers
      AUTH_SERVICE_URL: "http://auth_service:5001"
      GENERAL_CHAT_SERVICE_URL: "http://general_chat_service:5002"
      STUDY_SUPPORT_SERVICE_URL: "http://study_support_service:5003"
    ports:
      - "5008:5000"
  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    ports:
      - "5001:5001"
  general_chat_service:
    build:
      context: .
      dockerfile: services/general_chat_service/Dockerfile
    ports:
      - "5002:5002"
  study_support_service:
    build:
      context: .
      dockerfile: services/study_support_service/Dockerfile
    ports:
      - "5003:5003"
  data_service:
    build:
      context: .
      dockerfile: services/data_service/Dockerfile
    ports:
      - "5004:5004"
  response_service:
    build:
      context: .
      dockerfile: services/response_service/Dockerfile
    ports:
      - "5005:5005"
  system_prompt_service:
    build:
      context: .
      dockerfile: services/system_prompt_service/Dockerfile
    ports:
      - "5006:5006"
  training_service:
    build:
      context: .
      dockerfile: services/training_service/Dockerfile
    ports:
      - "5007:5007"
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      API_GATEWAY_URL: "http://api_gateway:5000/query"
    ports:
      - "7860:7860"
