---
name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  - push
jobs:
  Package and Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Code by Checkout
        uses: actions/checkout@v4
      - run: cd backend && npm i
      - run: npm run build
      - run: echo "Job Status:${{ job.status }}."
