name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd backend
      - run: npm i
      - run: npm run build

      - run: echo "Job Status:${{ job.status }}."
