# Generated by Django 4.1.5 on 2023-01-14 00:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_rename_about_user_biography_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, verbose_name='biography'),
        ),
    ]
