name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check my code
        uses: actions/checkout@v4
      - run: npm i
      - run: npm run build

      - run: echo "Job Status:${{ job.status }}."
